name: ai_mother_flutter
description: Trợ lý AI Mẹ hoạt động độc lập trên Android
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.0
  flutter_tts: ^3.6.3
  lottie: ^2.2.0
  path_provider: ^2.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.gif
    - assets/speak.wav